export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const ADD_CHILD = "ADD_CHILD"
export const CREATE_ACCOUNT = "CREATE_ACCOUNT"
export const CREATE_EVENT = "CREATE_EVENT"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const EDIT_USER = "EDIT_USER"
export const FIND_USER = "FIND_USER"
